# Generated by Django 3.1.1 on 2021-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleave',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
